import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../domain/entities.dart';
import '../core/money.dart';

Future<Uint8List> buildTransactionReceiptPdf({
  required LedgerTransaction transaction,
  String? businessName,
}) async {
  final doc = pw.Document();
  final dateStr = DateFormat.yMMMd().format(transaction.occurredAt);
  final amountStr = formatMoney(transaction.amountMinor);
  final typeStr =
      transaction.type == TxType.income ? 'Income' : 'Expense';

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.standard,
      build: (ctx) => pw.Padding(
        padding: const pw.EdgeInsets.all(40),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              businessName?.trim().isNotEmpty == true
                  ? businessName!.trim()
                  : 'Receipt',
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 24),
            pw.Text('Date: $dateStr'),
            pw.SizedBox(height: 8),
            pw.Text('Type: $typeStr'),
            pw.SizedBox(height: 8),
            pw.Text('Category: ${transaction.categoryName ?? '—'}'),
            pw.SizedBox(height: 8),
            pw.Text('Amount: $amountStr'),
            if (transaction.counterparty?.trim().isNotEmpty == true) ...[
              pw.SizedBox(height: 8),
              pw.Text('Payee / payer: ${transaction.counterparty}'),
            ],
            if (transaction.paymentMethod?.trim().isNotEmpty == true) ...[
              pw.SizedBox(height: 8),
              pw.Text('Payment method: ${transaction.paymentMethod}'),
            ],
            if (transaction.notes?.trim().isNotEmpty == true) ...[
              pw.SizedBox(height: 16),
              pw.Text('Notes:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.Text(transaction.notes!.trim()),
            ],
            pw.Spacer(),
            pw.Text(
              'Generated by Bennet',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          ],
        ),
      ),
    ),
  );
  return doc.save();
}
