import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/money.dart';
import '../domain/client_accounts.dart';

pw.Widget _wrapped(pw.TextStyle style, String text, {pw.TextAlign? align}) {
  return pw.Text(text, style: style, textAlign: align, softWrap: true);
}

Future<Uint8List> buildStatementPdf({
  required StatementPreview preview,
  String? businessName,
  int? statementNumber,
  DateTime? issuedAt,
  String? footerSecondary,
}) async {
  final doc = pw.Document();
  final df = DateFormat.yMMMd();
  final di = issuedAt != null ? DateFormat.yMMMd().format(issuedAt) : null;

  final headerTitle = businessName?.trim().isNotEmpty == true
      ? businessName!.trim()
      : 'Statement';

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.standard,
      margin: const pw.EdgeInsets.symmetric(horizontal: 36, vertical: 40),
      footer: (ctx) => pw.Padding(
        padding: const pw.EdgeInsets.only(top: 12),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.stretch,
          children: [
            if (footerSecondary?.trim().isNotEmpty == true)
              pw.Text(
                footerSecondary!.trim(),
                style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by Bennet',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
                ),
                pw.Text(
                  'Page ${ctx.pageNumber}',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
                ),
              ],
            ),
          ],
        ),
      ),
      build: (ctx) => [
        pw.Text(
          headerTitle,
          style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Statement',
          style: pw.TextStyle(fontSize: 13, color: PdfColors.grey800),
        ),
        if (statementNumber != null) ...[
          pw.SizedBox(height: 4),
          pw.Text(
            'Statement #$statementNumber'
            '${di != null ? ' · Issued $di' : ''}',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
        ],
        pw.SizedBox(height: 14),
        _wrapped(const pw.TextStyle(fontSize: 13), preview.client.displayName),
        _wrapped(
          pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          'Code: ${preview.client.clientCode}',
        ),
        pw.SizedBox(height: 12),
        pw.Text(
          'Period: ${df.format(preview.fromDate)} - ${df.format(preview.toDate)}',
        ),
        pw.SizedBox(height: 8),
        pw.Text('Opening balance: ${formatMoney(preview.openingBalanceMinor)}'),
        pw.Text('Closing balance: ${formatMoney(preview.closingBalanceMinor)}'),
        pw.SizedBox(height: 16),
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey400),
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(4),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(2),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey300),
              children: [
                _cellHdr('Date'),
                _cellHdr('Description'),
                _cellHdr('Amount'),
                _cellHdr('Balance'),
              ],
            ),
            for (final line in preview.lines)
              pw.TableRow(
                verticalAlignment: pw.TableCellVerticalAlignment.top,
                children: [
                  _cell(df.format(line.occurredAt)),
                  _cell(
                    line.detail != null && line.detail!.trim().isNotEmpty
                        ? '${line.label} - ${line.detail}'
                        : line.label,
                  ),
                  _cell(formatMoney(line.deltaMinor)),
                  _cell(formatMoney(line.runningBalanceMinor)),
                ],
              ),
          ],
        ),
      ],
    ),
  );
  return doc.save();
}

pw.Widget _cellHdr(String s) => pw.Padding(
  padding: const pw.EdgeInsets.all(6),
  child: pw.Text(s, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
);

pw.Widget _cell(String s) => pw.Padding(
  padding: const pw.EdgeInsets.all(6),
  child: _wrapped(const pw.TextStyle(fontSize: 10), s),
);
