// File generated by FlutterFire CLI — regenerate locally (needs network + credentials):
//   dart pub global activate flutterfire_cli
//   dart pub global run flutterfire_cli:flutterfire configure -p bennet-e696b -y ^
//     --overwrite-firebase-options --platforms=web,android,ios,macos,windows,linux ^
//     --android-package-name=com.bennet.bennet --service-account="PATH\to\adminsdk.json"
//
// Until then, placeholders allow compilation; Firebase calls fail until configured.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Bennet. Use `flutterfire configure` with your project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyCdsxJockXZo7wfi3UmEWvR6vntswHt0',
    appId: '1:981293790008:web:add6cf271a420e9ff487cd',
    messagingSenderId: '981293790008',
    projectId: 'bennet-e696b',
    authDomain: 'bennet-e696b.firebaseapp.com',
    storageBucket: 'bennet-e696b.firebasestorage.app',
    measurementId: 'G-YE7WHTCM8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98P3NHaKX9xwIpvIU7Dkv4ZdtAKGgcJE',
    appId: '1:981293790008:android:0c2e43464bda2fcbf487cd',
    messagingSenderId: '981293790008',
    projectId: 'bennet-e696b',
    storageBucket: 'bennet-e696b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzieAUE-aqzuaCt7jYu1T1hEtUhwNx0EA',
    appId: '1:981293790008:ios:28ced7250a15658df487cd',
    messagingSenderId: '981293790008',
    projectId: 'bennet-e696b',
    storageBucket: 'bennet-e696b.firebasestorage.app',
    iosBundleId: 'com.bennet.bennet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzieAUE-aqzuaCt7jYu1T1hEtUhwNx0EA',
    appId: '1:981293790008:ios:28ced7250a15658df487cd',
    messagingSenderId: '981293790008',
    projectId: 'bennet-e696b',
    storageBucket: 'bennet-e696b.firebasestorage.app',
    iosBundleId: 'com.bennet.bennet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyCdsxJockXZo7wfi3UmEWvR6vntswHt0',
    appId: '1:981293790008:web:200a31451ebfb326f487cd',
    messagingSenderId: '981293790008',
    projectId: 'bennet-e696b',
    authDomain: 'bennet-e696b.firebaseapp.com',
    storageBucket: 'bennet-e696b.firebasestorage.app',
    measurementId: 'G-5TZ0337NW6',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'bennet-e696b',
    authDomain: 'bennet-e696b.firebaseapp.com',
    storageBucket: 'bennet-e696b.appspot.com',
  );
}